### ISSUE TITLE
Why using getServerSideProps rather than getStaticProps

### ISSUE THREAD

**Issue by Combo819** [jakeherp/portfolio#860]
Hi, I am new to next.js. I have a question that why `getServerSideProps` is used but not `getStaticProps`?  In my perspective, `getStaticProps` is called when generating static html files from next.js. However, `getServerSideProps` is for server-side render.   
For this portfolio project, the data is very simple, which makes the server-side render unnecessary. Perhas generate static files with `getStaticProps` is more lightweigh and convenient.  
BTW, the portfolio looks very beautiful. Really like your work.

**Comment by jakeherp** [comment]
This was changed a while back. Closing.
