### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by Rajesh-Royal** [jakeherp/portfolio#877]
- The close button is not working after the menu is open.
- The case-study mockup z-index overlaps with the menu z-index.
![image](https://user-images.githubusercontent.com/24524924/201069493-1c57eb5f-d223-4999-8532-54e071eda1e1.png)

**Tested on**

- Windows 10, chrome's latest version till today.
- Android 12.

**Comment by jakeherp** [comment]
I cannot reproduce this problem on my machines. Tested on Mac with latest Chrome as well as iOS 16.2 and Android 13.

**Comment by jakeherp** [comment]
Closing as a refresh will be released soon.
