### ISSUE TITLE
Prerender error

### ISSUE THREAD

**Issue by ilovemusicgg** [jakeherp/portfolio#893]
![IMG_6562](https://user-images.githubusercontent.com/123872500/229339022-58cc4722-744e-470f-aaa7-36968590efbb.jpeg)
How to fix?

**Comment by jakeherp** [comment]
These are dependent on Sanity as a CMS. I'll add documentation on this soon.

Once you have signed up for Sanity, you have to set the environment variables (see `.env.example`), the schemas for Sanity are included in the code base, so you should be able to just use those to get up and running. You can access your Sanity Studio running locally on http://localhost:3000/studio.

Let me know if you need any further help with this.
